export const GET_ALL_REQUIREMENT_FORMS = "GET_ALL_REQUIREMENT_FORMS";
export const GET_ALL_REQUIREMENT_FORMS_SUCCESS =
  "GET_ALL_REQUIREMENT_FORMS_SUCCESS";
export const GET_ALL_REQUIREMENT_FORMS_FAILURE =
  "GET_ALL_REQUIREMENT_FORMS_FAILURE";
export const CLEAR_GET_ALL_REQUIREMENT_FORMS =
  "CLEAR_GET_ALL_REQUIREMENT_FORMS";
