export const GET_PACKAGES = "GET_PACKAGES";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCESS";
export const GET_PACKAGES_FAILURE = "GET_PACKAGES_FAILURE";
export const ADD_DISCOUNT_AMOUNT = "ADD_DISCOUNT_AMOUNT";
export const ADD_DISCOUNT_AMOUNT_SUCCESS = "ADD_DISCOUNT_AMOUNT_SUCESS";
export const ADD_DISCOUNT_AMOUNT_FAILURE = "ADD_DISCOUNT_AMOUNT_FAILURE";
export const ADD_DISCOUNT_AMOUNT_CLEAR = "ADD_DISCOUNT_AMOUNT_CLEAR";
export const ADD_CHECKOUT = "ADD_CHECKOUT";
export const ADD_CHECKOUT_SUCCESS = "ADD_CHECKOUT_SUCESS";
export const ADD_CHECKOUT_FAILURE = "ADD_CHECKOUT_FAILURE";

export const CREATE_PACKAGE = "CREATE_PACKAGE";
export const CREATE_PACKAGE_SUCCESS = "CREATE_PACKAGE_SUCESS";
export const CREATE_PACKAGE_FAILURE = "CREATE_PACKAGE_FAILURE";
export const CREATE_PACKAGE_CLEAR = "CREATE_PACKAGE_CLEAR";
