export const POST_SUSPEND_REQUEST = "POST_SUSPEND_REQUEST";
export const POST_SUSPEND_REQUEST_SUCCESS = "POST_SUSPEND_REQUEST_SUCESS";
export const POST_SUSPEND_REQUEST_FAILURE = "POST_SUSPEND_REQUEST_FAILURE";
