export const GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT =
  "GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT";
export const GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT_SUCCESS =
  "GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT_SUCCESS";
export const GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT_FAILURE =
  "GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT_FAILURE";
export const CLEAR_GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT =
  "CLEAR_GET_ALL_ELOUNGE_VISIT_FOR_MANAGEMENT";

export const GET_ASSIGN_ELOUNGE_SALE_USER = "GET_ASSIGN_ELOUNGE_SALE_USER";
export const GET_ASSIGN_ELOUNGE_SALE_USER_SUCCESS =
  "GET_ASSIGN_ELOUNGE_SALE_USER_SUCCESS";
export const GET_ASSIGN_ELOUNGE_SALE_USER_FAILURE =
  "GET_ASSIGN_ELOUNGE_SALE_USER_FAILURE";
export const CLEAR_GET_ASSIGN_ELOUNGE_SALE_USER =
  "CLEAR_GET_ASSIGN_ELOUNGE_SALE_USER";
