export const GET_SIGNUP_COUNTS_FOR_LEAD = "GET_SIGNUP_COUNTS_FOR_LEAD";
export const GET_SIGNUP_COUNTS_FOR_LEAD_SUCCESS =
  "GET_SIGNUP_COUNTS_FOR_LEAD_SUCCESS";
export const GET_SIGNUP_COUNTS_FOR_LEAD_FAILURE =
  "GET_SIGNUP_COUNTS_FOR_LEAD_FAILURE";
export const CLEAR_GET_SIGNUP_COUNTS_FOR_LEAD =
  "CLEAR_GET_SIGNUP_COUNTS_FOR_LEAD";

export const GET_SUBSCRIBER_COUNTS_FOR_LEAD = "GET_SUBSCRIBER_COUNTS_FOR_LEAD";
export const GET_SUBSCRIBER_COUNTS_FOR_LEAD_SUCCESS =
  "GET_SUBSCRIBER_COUNTS_FOR_LEAD_SUCCESS";
export const GET_SUBSCRIBER_COUNTS_FOR_LEAD_FAILURE =
  "GET_SUBSCRIBER_COUNTS_FOR_LEAD_FAILURE";
export const CLEAR_GET_SUBSCRIBER_COUNTS_FOR_LEAD =
  "CLEAR_GET_SUBSCRIBER_COUNTS_FOR_LEAD";

export const GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD =
  "GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD";
export const GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD_SUCCESS =
  "GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD_SUCCESS";
export const GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD_FAILURE =
  "GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD_FAILURE";
export const CLEAR_GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD =
  "CLEAR_GET_ALL_SALE_USER_INVENTORIES_FOR_LEAD";

export const GET_ALL_TRANSACTION_HISTORY = "GET_ALL_TRANSACTION_HISTORY";
export const GET_ALL_TRANSACTION_HISTORY_SUCCESS =
  "GET_ALL_TRANSACTION_HISTORY_SUCCESS";
export const GET_ALL_TRANSACTION_HISTORY_FAILURE =
  "GET_ALL_TRANSACTION_HISTORY_FAILURE";
export const CLEAR_GET_ALL_TRANSACTION_HISTORY =
  "CLEAR_GET_ALL_TRANSACTION_HISTORY";
