// getcounts
export const GET_COUNTS = "GET_COUNTS";
export const GET_COUNTS_SUCCESS = "GET_COUNTS_SUCESS";
export const GET_COUNTS_FAILURE = "GET_COUNTS_FAILURE";

// getearninghistory
export const GET_EARNING_HISTORY = "GET_EARNING_HISTORY";
export const GET_EARNING_HISTORY_SUCCESS = "GET_EARNING_HISTORY_SUCESS";
export const GET_EARNING_HISTORY_FAILURE = "GET_EARNING_HISTORY_FAILURE";

// geteallsessions
export const GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
export const GET_ALL_SESSIONS_SUCCESS = "GET_ALL_SESSIONS_SUCESS";
export const GET_ALL_SESSIONS_FAILURE = "GET_ALL_SESSIONS_FAILURE";

// geteallbookingsessions
export const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS";
export const GET_ALL_BOOKINGS_SUCCESS = "GET_ALL_BOOKINGS_SUCESS";
export const GET_ALL_BOOKINGS_FAILURE = "GET_ALL_BOOKINGS_FAILURE";

// deletesession
export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCESS";
export const DELETE_SESSION_FAILURE = "DELETE_SESSION_FAILURE";

// addsession
export const ADD_SESSION = "ADD_SESSION";
export const ADD_SESSION_SUCCESS = "ADD_SESSION_SUCESS";
export const ADD_SESSION_FAILURE = "ADD_SESSION_FAILURE";
