// Login
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
// SIGNUP
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
// VERIFICATION
export const VERIFICATION = "VERIFICATION";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCESS";
export const VERIFICATION_FAILURE = "VERIFICATION_FAILURE";
// TOUR_CHECK
export const SENDOTP = "SENDOTP";
export const SENDOTP_SUCCESS = "SENDOTP_SUCESS";
export const SENDOTP_FAILURE = "SENDOTP_FAILURE";


export const TOUR_CHECK = "TOUR_CHECK";
export const TOUR_CHECK_SUCCESS = "TOUR_CHECK_SUCESS";
export const TOUR_CHECK_FAILURE = "TOUR_CHECK_FAILURE";