export const GET_ALL_CUSTOM_PACKAGES = "GET_ALL_CUSTOM_PACKAGES";
export const GET_ALL_CUSTOM_PACKAGES_SUCCESS =
  "GET_ALL_CUSTOM_PACKAGES_SUCCESS";
export const GET_ALL_CUSTOM_PACKAGES_FAILURE =
  "GET_ALL_CUSTOM_PACKAGES_FAILURE";
export const CLEAR_GET_ALL_CUSTOM_PACKAGES = "CLEAR_GET_ALL_CUSTOM_PACKAGES";
