export const GET_WALLET_NOT_FOR_USER_LIST = "GET_WALLET_NOT_FOR_USER_LIST";
export const GET_WALLET_NOT_FOR_USER_LIST_SUCCESS =
  "GET_WALLET_NOT_FOR_USER_LIST_SUCCESS";
export const GET_WALLET_NOT_FOR_USER_LIST_FAILURE =
  "GET_WALLET_NOT_FOR_USER_LIST_FAILURE";

export const GET_WALLET_BALANCE_NOT_FOR_USER =
  "GET_WALLET_BALANCE_NOT_FOR_USER";
export const GET_WALLET_BALANCE_NOT_FOR_USER_SUCCESS =
  "GET_WALLET_BALANCE_NOT_FOR_USER_SUCCESS";
export const GET_WALLET_BALANCE_NOT_FOR_USER_FAILURE =
  "GET_WALLET_BALANCE_NOT_FOR_USER_FAILURE";

export const ADD_WITHDRAW_REQUEST_NOT_FOR_USER =
  "ADD_WITHDRAW_REQUEST_NOT_FOR_USER";
export const ADD_WITHDRAW_REQUEST_NOT_FOR_USER_SUCCESS =
  "ADD_WITHDRAW_REQUEST_NOT_FOR_USER_SUCCESS";
export const ADD_WITHDRAW_REQUEST_NOT_FOR_USER_FAILURE =
  "ADD_WITHDRAW_REQUEST_NOT_FOR_USER_FAILURE";

export const GET_ALL_BANKS_LISTS_NOT_FOR_USER =
  "GET_ALL_BANKS_LISTS_NOT_FOR_USER";
export const GET_ALL_BANKS_LISTS_NOT_FOR_USER_SUCCESS =
  "GET_ALL_BANKS_LISTS_NOT_FOR_USER_SUCCESS";
export const GET_ALL_BANKS_LISTS_NOT_FOR_USER_FAILURE =
  "GET_ALL_BANKS_LISTS_NOT_FOR_USER_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
