version: 0.2
phases:
  install:
    commands:
      - echo runtime installed
      - n 14
  pre_build:
    commands:
      - rm -rf node_modules
      - rm -f package-lock.json
      - npm cache clean --force
      - echo installing source npm dependencies
      - npm install
  build:
    commands:
      - echo bilding
      - export NODE_OPTIONS="--max-old-space-size=3072"
      - npm run build
  post_build:
    commands:
      - echo build complete on `date`
      - aws s3 sync ./build s3://adminportal.propertywallet.pk/
      - aws cloudfront create-invalidation --distribution-id E3VEB7BDHOWWVL --paths '/*'
