export const MILESTONE = "MILESTONE";
export const MILESTONE_SUCCESS = "MILESTONE_SUCCESS";
export const MILESTONE_FAILURE = "MILESTONE_FAILURE";

export const ASSIGN_MILESTONE = "ASSIGN_MILESTONE";
export const ASSIGN_MILESTONE_SUCCESS = "ASSIGN_MILESTONE_SUCCESS";
export const ASSIGN_MILESTONE_FAILURE = "ASSIGN_MILESTONE_FAILURE";

export const GET_MILESTONE_CERTIFICATE = "GET_MILESTONE_CERTIFICATE";
export const GET_MILESTONE_CERTIFICATE_SUCCESS =
  "GET_MILESTONE_CERTIFICATE_SUCCESS";
export const GET_MILESTONE_CERTIFICATE_FAILURE =
  "GET_MILESTONE_CERTIFICATE_FAILURE";
