export const GET_WALLET_LIST = "GET_WALLET_LIST"
export const GET_WALLET_LIST_SUCCESS = "GET_WALLET_LIST_SUCCESS"
export const GET_WALLET_LIST_FAILURE = "GET_WALLET_LIST_FAILURE"

export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE"
export const GET_WALLET_BALANCE_SUCCESS = "GET_WALLET_BALANCE_SUCCESS"
export const GET_WALLET_BALANCE_FAILURE = "GET_WALLET_BALANCE_FAILURE"

export const ADD_WITHDRAW_REQUEST = "ADD_WITHDRAW_REQUEST"
export const ADD_WITHDRAW_REQUEST_SUCCESS = "ADD_WITHDRAW_REQUEST_SUCCESS"
export const ADD_WITHDRAW_REQUEST_FAILURE = "ADD_WITHDRAW_REQUEST_FAILURE"

export const GET_ALL_BANKS_LISTS = "GET_ALL_BANKS_LISTS"
export const GET_ALL_BANKS_LISTS_SUCCESS = "GET_ALL_BANKS_LISTS_SUCCESS"
export const GET_ALL_BANKS_LISTS_FAILURE = "GET_ALL_BANKS_LISTS_FAILURE"

export const GET_USER_PROFILE = "GET_USER_PROFILE"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE"
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE"