export const GET_SALE_ORDER = "GET_SALE_ORDER";
export const GET_SALE_ORDER_SUCCESS = "GET_SALE_ORDER_SUCCESS";
export const GET_SALE_ORDER_FAILURE = "GET_SALE_ORDER_FAILURE";

export const GET_SALE_ORDER_GRAPH = "GET_SALE_ORDER_GRAPH";
export const GET_SALE_ORDER_GRAPH_SUCCESS = "GET_SALE_ORDER_GRAPH_SUCCESS";
export const GET_SALE_ORDER_GRAPH_FAILURE = "GET_SALE_ORDER_GRAPH_FAILURE";

export const GET_SALE_ORDER_COMMISSON = "GET_SALE_ORDER_COMMISSON";
export const GET_SALE_ORDER_COMMISSON_SUCCESS = "GET_SALE_ORDER_COMMISSON_SUCCESS";
export const GET_SALE_ORDER_COMMISSON_FAILURE = "GET_SALE_ORDER_COMMISSON_FAILURE";