// FORGOT PASSWORD WITH EMAIL
export const FORGOT_PASSWORD_WITH_EMAIL = "FORGOT_PASSWORD_WITH_EMAIL";
export const FORGOT_PASSWORD_WITH_EMAIL_SUCCESS =
  "FORGOT_PASSWORD_WITH_EMAIL_SUCESS";
export const FORGOT_PASSWORD_WITH_EMAIL_FAILURE =
  "FORGOT_PASSWORD_WITH_EMAIL_FAILURE";

// FORGOT PASSWORD OTP Verification
export const FORGOT_PASSWORD_OTP_VERIFY = "FORGOT_PASSWORD_OTP_VERIFY";
export const FORGOT_PASSWORD_OTP_VERIFY_SUCCESS =
  "FORGOT_PASSWORD_OTP_VERIFY_SUCESS";
export const FORGOT_PASSWORD_OTP_VERIFY_FAILURE =
  "FORGOT_PASSWORD_OTP_VERIFY_FAILURE";

// FORGOT PASSWORD OTP Verification
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
