export const GET_ALL_REQUIREMENT_FORMS_FOR_LEAD =
  "GET_ALL_REQUIREMENT_FORMS_FOR_LEAD";
export const GET_ALL_REQUIREMENT_FORMS_FOR_LEAD_SUCCESS =
  "GET_ALL_REQUIREMENT_FORMS_FOR_LEAD_SUCCESS";
export const GET_ALL_REQUIREMENT_FORMS_FOR_LEAD_FAILURE =
  "GET_ALL_REQUIREMENT_FORMS_FOR_LEAD_FAILURE";
export const CLEAR_GET_ALL_REQUIREMENT_FORMS_FOR_LEAD =
  "CLEAR_GET_ALL_REQUIREMENT_FORMS_FOR_LEAD";
