export const REQUIREMENT_FORM = "REQUIREMENT_FORM";
export const REQUIREMENT_FORM_SUCCESS = "REQUIREMENT_FORM_SUCCESS";
export const REQUIREMENT_FORM_FAILURE = "REQUIREMENT_FORM_FAILURE";
export const CLEAR_REQUIREMENT_FORM = "CLEAR_REQUIREMENT_FORM";

export const GET_REQUIREMENT_FORM = "GET_REQUIREMENT_FORM";
export const GET_REQUIREMENT_FORM_SUCCESS = "GET_REQUIREMENT_FORM_SUCCESS";
export const GET_REQUIREMENT_FORM_FAILURE = "GET_REQUIREMENT_FORM_FAILURE";
export const CLEAR_GET_REQUIREMENT_FORM = "CLEAR_GET_REQUIREMENT_FORM";

export const UPDATE_REQUIREMENR_FORM = "UPDATE_REQUIREMENR_FORM";
export const UPDATE_REQUIREMENR_FORM_SUCCESS =
  "UPDATE_REQUIREMENR_FORM_SUCCESS";
export const UPDATE_REQUIREMENR_FORM_FAILURE =
  "UPDATE_REQUIREMENR_FORM_FAILURE";
export const CLEAR_UPDATE_REQUIREMENR_FORM = "CLEAR_UPDATE_REQUIREMENR_FORM";
