const ENDPOINT = {
  auth: {
    login: "company-auth/login",
    register: "company-auth/registration",
    createCompany: "company",
    getCompany: "company",
    createBusiness: "business",
    forgetPasswordEmail: "company-user/forgetPasswordByEmail",
    resetPassword: "company-user/forgetPassword/ByIdAndNewPssword",
    google: "company-auth/sso/google",
    facebook: "company-auth/sso/facebook",
    decodePasswordLink: "company-user/decodeUrl",
  },
  dashboard: {
    getAllUsers: "",
    getHoursChart: "company-user-attendance/AdminSideDesdhboardForChart",
    getAttendance: "company-user-attendance/AdminSideDesdhboardForTable",
    upcommingBirthdays: "Company-user/UpcommingBirthdays",
    upCommingAnniversaries: "Company-user/UpcommingAnniverseries",
  },
  chatBot: {
    getAllChat: "chatbot/getAllChats/ByUserId",
    getChatHistoryByChatId: "chatbot/chatHistoryByChatId",
    getRemainingCredits: "chatbot/getCompany/CountsRemaining",
    updateToneOfVoice: "chatbot/ChatUpdate",
  },
  business: {
    getIndustry: "company-auth/findAllIndustryData",
    getRole: "company-auth/findAllRolesData",
    getBusinessById: "business",
    currency: "currency",
    language: "language",
    country: "country",
    businessPlan: "business/business-plan",
    updateBusinessPlan: "business/update/business-plan/languageById",
    getBusinessPlans: "business/all-business-plan",
    companyUsers: "company-user",
    updatecompanyUser: "company-user/companyUserUpdate",
    updateUserPreferences: "company-user/update-user-preferences",
    getBusinesses: "company/getBusinesses",
    updateUserPassword: "company-auth/new-password-input",
    getCompany: "company",
    deleteCompanyUser: "company-auth/updateUser/UnActive",
  },
  questions: {
    getQuestion: "question/by-topic-id",
    createAnswer: "answer",
    updateAnswer: "answer",
    getAnswerByIds: "answer",
    postTableValues: "table-values",
    getTableValues: "table-values",
    getAllTopic: "topic",
    createContent: "answer/AddContent/forAnswers",
    getQuestionById: "question",
    linkedAnswers: "linked-answers",
    getOneLinkedAnswer: "answer/getOneLinkedAnswer",
    createSummary: "answer/AddContent/forSummary",
  },
  editPlan: {
    chapter: "chapter",
    contentByChapterIdAndPlanId:
      "business-plan-content/chapter/:chapterId/businessPlan/:businessPlanId",
    updatecontent: "business-plan-content",
  },
  comingSoon: {
    interestedLeads: "interested-leads",
  },
  productPromotion: {
    createProductPromotion: "business/promotion",
    productPromotionInfo: "business/BusinessPromotionInfo",
    productPromotions: "business/promotions",
    businessPromotions: "business/businesspromotions",
    postUpvote: "business/promotion",
    businessStats: "business/businesspromotions/Counts",
    productPromotionStats: "business/CountsByBusinessPromotionId",
    addReview: "business/promotion",
    reviewReply: "business/ReplyByReviewId",
    deletePhoto: "business/removePhoto",
    deleteVideo: "business/removeVideo",
    allBusinessPromotions: "business/Allbusiness/promotions",
    addView: "business/promotion/addview",
  },
  addNewIdea: {
    ideaValidation: "idea-answer/ideaValidation",
    ideaQuestion: "idea-question",
    ideaAnswer: "idea-answer",
    getideaAnswerByIdeaValidationId: "idea-answer/byIdeaValidationId",
    postIdeaValidaitonId: "idea-answer/add/IdeaContent",
  },
  ViewPlanAndDownloadPdf: {
    businessPlanContentBusinessPlan: "business-plan-content/businessPlan",
    isOnFreePackage: "company-user/check/Package",
  },
  ideaEvaluation: {
    ideaAnswerValidation: "idea-answer/ideaValidation",
  },
  ideaValidationById: {
    ideaValidationByBusinessId: "idea-answer/ideaValidation/byUser",
  },
  businessPlanInfo: {
    businessPlanInfo: "question/businessPlan/complete-info",
  },
  businessPlanSetup: {
    allElements: "business/businessPlan/all-elements",
    products: "products",
    getProduct: "products/get-one",
    equity: "equity",
    getEquity: "equity/get-one",
    services: "services",
    getService: "services/get-one",
    staffing: "staffing",
    getStaff: "staffing/get-one",
    multipleEquities: "equity/multipleEquities",
    multipleStaffing: "staffing/multipleStaffing",
  },
  businessToolKit: {
    getBpdCanvasIdsByPlanId: "business-plan-documents/businessModelCanvasData",
    getBusinessModelCanvasData: "business-plan-documents/business-modal-canvas",
  },
  checkOutPost: {
    updateSubscription: "stripe/update-subscription",
    postPaymentMethod: "stripe/payment-methods/add",
    getPaymentMethod: "stripe/payment-methods",
    createSubscription: "stripe/create-subscription",
    addOnPay: "stripe/addOn/pay",
    verifyCoupon: "stripe/coupon/validity",
    updatePaymentMethod: "stripe/payment-methods/update",
  },
  subscriptionPlan: {
    getPackage: "package",
    getAddOns: "package/add-Ons",
    getSubscribedPlan: "stripe/subscription/details",
  },
  businessCount: {
    getBusinessCount: "company/details/counts",
  },
  decode: {
    decodeUrlApi: "affilate-user/decodeUrl",
  },
  pitchDeck: {
    pitch: "pitch-deck",
    question: "pitch-deck-questions",
    answer: "pitch-deck-answers",
    getAttemptedAnswer:
      "pitch-deck-answers/forAnswer/ByquestionId/AndPitchDeckId",
  },
  blogs: {
    getBlogForUser: "blogs/forUser/getAllBlogs",
    getBlogsCategory: "blogs/forUser/getAllBlogsCategory",
    getBlogById: "blogs/get-one",
  },
  requestSupport: {
    supportTickets: "support-tickets",
  },
  websiteCounts: {
    websiteCounts: "company-auth/addWebSiteCount",
  },
};

export { ENDPOINT };
