export const GET_ALL_SUBSCRIBERS = "GET_ALL_SUBSCRIBERS";
export const GET_ALL_SUBSCRIBERS_SUCCESS = "GET_ALL_SUBSCRIBERS_SUCESS";
export const GET_ALL_SUBSCRIBERS_FAILURE = "GET_ALL_SUBSCRIBERS_FAILURE";

export const GET_ALL_SIGNUPS = "GET_ALL_SIGNUPS";
export const GET_ALL_SIGNUPS_SUCCESS = "GET_ALL_SIGNUPS_SUCESS";
export const GET_ALL_SIGNUPS_FAILURE = "GET_ALL_SIGNUPS_FAILURE";

export const GET_ALL_TransactionSaleUser = "GET_ALL_TransactionSaleUser";
export const GET_ALL_TransactionSaleUser_SUCCESS =
  "GET_ALL_TransactionSaleUser_SUCESS";
export const GET_ALL_TransactionSaleUser_FAILURE =
  "GET_ALL_TransactionSaleUser_FAILURE";

export const GET_PW_INVENTORY = "GET_PW_INVENTORY";
export const GET_PW_INVENTORY_SUCCESS = "GET_PW_INVENTORY_SUCESS";
export const GET_PW_INVENTORY_FAILURE = "GET_PW_INVENTORY_FAILURE";

export const GET_SALE_ORDER_BY_ID = "GET_SALE_ORDER_BY_ID";
export const GET_SALE_ORDER_BY_ID_SUCCESS = "GET_SALE_ORDER_BY_ID_SUCESS";
export const GET_SALE_ORDER_BY_ID_FAILURE = "GET_SALE_ORDER_BY_ID_FAILURE";

export const GET_TOKEN_BY_ID = "GET_TOKEN_BY_ID";
export const GET_TOKEN_BY_ID_SUCCESS = "GET_TOKEN_BY_ID_SUCESS";
export const GET_TOKEN_BY_ID_FAILURE = "GET_TOKEN_BY_ID_FAILURE";

export const GET_ALL_TARGET = "GET_ALL_TARGET";
export const GET_ALL_TARGET_SUCCESS = "GET_ALL_TARGET_SUCESS";
export const GET_ALL_TARGET_FAILURE = "GET_ALL_TARGET_FAILURE";

export const GET_ALL_TRANSACTION_HISTORY = "GET_ALL_TRANSACTION_HISTORY";
export const GET_ALL_TRANSACTION_HISTORY_SUCCESS =
  "GET_ALL_TRANSACTION_HISTORY_SUCCESS";
export const GET_ALL_TRANSACTION_HISTORY_FAILURE =
  "GET_ALL_TRANSACTION_HISTORY_FAILURE";
export const CLEAR_GET_ALL_TRANSACTION_HISTORY =
  "CLEAR_GET_ALL_TRANSACTION_HISTORY";
