export const GET_ALL_VISITS = "GET_ALL_VISITS"
export const GET_ALL_VISITS_SUCCESS = "GET_ALL_VISITS_SUCCESS"
export const GET_ALL_VISITS_FAILURE = "GET_ALL_VISITS_FAILURE"

export const ADD_NEW_VISIT = "ADD_NEW_VISIT"
export const ADD_NEW_VISIT_SUCCESS = "ADD_NEW_VISIT_SUCCESS"
export const ADD_NEW_VISIT_FAILURE = "ADD_NEW_VISIT_FAILURE"

export const EDIT_VISIT = "EDIT_VISIT"
export const EDIT_VISIT_SUCCESS = "EDIT_VISIT_SUCCESS"
export const EDIT_VISIT_FAILURE = "EDIT_VISIT_FAILURE"

export const DELETE_VISIT = "DELETE_VISIT"
export const DELETE_VISIT_SUCCESS = "DELETE_VISIT_SUCCESS"
export const DELETE_VISIT_FAILURE = "DELETE_VISIT_FAILURE"

export const UPLOAD_IMAGES = "UPLOAD_IMAGES"
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS"
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE"