export const GET_VISITED_SALES_USER_FOR_LEAD =
  "GET_VISITED_SALES_USER_FOR_LEAD";
export const GET_VISITED_SALES_USER_FOR_LEAD_SUCCESS =
  "GET_VISITED_SALES_USER_FOR_LEAD_SUCCESS";
export const GET_VISITED_SALES_USER_FOR_LEAD_FAILURE =
  "GET_VISITED_SALES_USER_FOR_LEAD_FAILURE";
export const CLEAR_GET_VISITED_SALES_USER_FOR_LEAD =
  "CLEAR_GET_VISITED_SALES_USER_FOR_LEAD";

export const GET_VISITED_FREELANCER_USER_FOR_LEAD =
  "GET_VISITED_FREELANCER_USER_FOR_LEAD";
export const GET_VISITED_FREELANCER_USER_FOR_LEAD_SUCCESS =
  "GET_VISITED_FREELANCER_USER_FOR_LEAD_SUCCESS";
export const GET_VISITED_FREELANCER_USER_FOR_LEAD_FAILURE =
  "GET_VISITED_FREELANCER_USER_FOR_LEAD_FAILURE";
export const CLEAR_GET_VISITED_FREELANCER_USER_FOR_LEAD =
  "CLEAR_GET_VISITED_FREELANCER_USER_FOR_LEAD";

export const GET_VISITED_AGENT_USER_FOR_LEAD =
  "GET_VISITED_AGENT_USER_FOR_LEAD";
export const GET_VISITED_AGENT_USER_FOR_LEAD_SUCCESS =
  "GET_VISITED_AGENT_USER_FOR_LEAD_SUCCESS";
export const GET_VISITED_AGENT_USER_FOR_LEAD_FAILURE =
  "GET_VISITED_AGENT_USER_FOR_LEAD_FAILURE";
export const CLEAR_GET_VISITED_AGENT_USER_FOR_LEAD =
  "CLEAR_GET_VISITED_AGENT_USER_FOR_LEAD";
