export const SALE_USER_INVENTORIES_BY_ELOUNGE =
  "SALE_USER_INVENTORIES_BY_ELOUNGE";
export const SALE_USER_INVENTORIES_BY_ELOUNGE_SUCCESS =
  "SALE_USER_INVENTORIES_BY_ELOUNGE_SUCCESS";
export const SALE_USER_INVENTORIES_BY_ELOUNGE_FAILURE =
  "SALE_USER_INVENTORIES_BY_ELOUNGE_FAILURE";

export const SIGN_UP_COUNTS = "SIGN_UP_COUNTS";
export const SIGN_UP_COUNTS_SUCCESS = "SIGN_UP_COUNTS_SUCCESS";
export const SIGN_UP_COUNTS_FAILURE = "SIGN_UP_COUNTS_FAILURE";

export const SUBCRIBER_COUNTS = "SUBCRIBER_COUNTS";
export const SUBCRIBER_COUNTS_SUCCESS = "SUBCRIBER_COUNTS_SUCCESS";
export const SUBCRIBER_COUNTS_FAILURE = "SUBCRIBER_COUNTS_FAILURE";

export const HISTORY_FOR_MANAGEMENT = "HISTORY_FOR_MANAGEMENT";
export const HISTORY_FOR_MANAGEMENT_SUCCESS = "HISTORY_FOR_MANAGEMENT_SUCCESS";
export const HISTORY_FOR_MANAGEMENT_FAILURE = "HISTORY_FOR_MANAGEMENT_FAILURE ";
export const CLEAR_HISTORY_FOR_MANAGEMENT = "CLEAR_HISTORY_FOR_MANAGEMENT";

export const MY_TRANSACTION_HISTORY = "MY_TRANSACTION_HISTORY";
export const MY_TRANSACTION_HISTORY_SUCCESS = "MY_TRANSACTION_HISTORY_SUCCESS";
export const MY_TRANSACTION_HISTORY_FAILURE = "MY_TRANSACTION_HISTORY_FAILURE ";
export const CLEAR_MY_TRANSACTION_HISTORY = "CLEAR_HISTORY_FOR_MANAGEMENT";

export const GET_LEAD_LIST_FOR_DROP_DOWN = "GET_LEAD_LIST_FOR_DROP_DOWN";
export const GET_LEAD_LIST_FOR_DROP_DOWN_SUCCESS =
  "GET_LEAD_LIST_FOR_DROP_DOWN_SUCCESS";
export const GET_LEAD_LIST_FOR_DROP_DOWN_FAILURE =
  "GET_LEAD_LIST_FOR_DROP_DOWN_FAILURE ";
export const CLEAR_GET_LEAD_LIST_FOR_DROP_DOWN =
  "CLEAR_GET_LEAD_LIST_FOR_DROP_DOWN";

export const GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS =
  " GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS";
export const GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS_SUCCESS =
  " GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS_SUCCESS";
export const GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS_FAILURE =
  " GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS_FAILURE ";
export const CLEAR_GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS =
  "CLEAR_GET_ALL_ASSIGN_SALE_USER_BY_LEAD_ID_FOR_ELOUNGE_USERS";
